# Generated by Django 5.0 on 2024-06-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("whatsapp", models.CharField(max_length=30)),
                ("gender", models.CharField(default="Male", max_length=20)),
                ("institute", models.CharField(max_length=200, null=True)),
                ("field_of_study", models.CharField(max_length=200, null=True)),
                (
                    "years_education",
                    models.DecimalField(decimal_places=2, max_digits=2, null=True),
                ),
                ("region", models.CharField(max_length=200, null=True)),
                ("facebook", models.CharField(max_length=300, null=True)),
                ("instagram", models.CharField(max_length=300, null=True)),
                ("linkedin", models.CharField(max_length=300, null=True)),
                ("experience", models.CharField(max_length=2000, null=True)),
                ("application_datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="appsrc.application",
                    ),
                ),
            ],
        ),
    ]
