# Generated by Django 5.0 on 2024-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appsrc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="years_education",
            field=models.FloatField(null=True),
        ),
    ]
